---
- name: "build essential"
  sudo: yes
  apt:
    name: "build-essential"
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: "nvm repository"
  git:
    repo: "{{ nodejs_nvm_git_repo }}"
    dest: "{{ nodejs_nvm_dir }}"

- name: "nvm in path"
  lineinfile:
    dest: "~/.bashrc"
    line: 'export PATH="$PATH:$HOME/.nvm/bin"'
    state: present

- name: "source nvm bashrc"
  lineinfile:
    dest: "~/.bashrc"
    line: "source ~/.nvm/nvm.sh"
    state: present

- name: "node installed"
  script: "node-install.sh {{ nodejs_version }} {{ nodejs_nvm_dir }}/.node-{{ nodejs_version }}"
  changed_when: false

- name: "source .bashrc"
  shell: ". ~/.bashrc"
  changed_when: false

- name: "node version"
  shell: "cat /home/{{ ansible_user_id }}/.node-version"
  register: _node_ver
  changed_when: false

- include: "packages.yml"
